# Generated by Django 3.2.5 on 2022-06-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('car_pic', models.ImageField(blank=True, upload_to='car_pics')),
                ('bouwjaar', models.IntegerField()),
                ('km_stand', models.FloatField()),
                ('merk', models.CharField(max_length=256)),
            ],
        ),
    ]
